package com.example.toiletapi.auth.model;

/** 감사 로그에 남기는 보안·관리 행위 코드다. */
public enum AuditAction {
    USER_RESTORED,
    ROLE_GRANTED,
    ROLE_REVOKED,
    REPORT_APPROVED,
    REPORT_REJECTED,
    USER_SUSPENDED,
    USER_WITHDRAWN,
    COORDINATE_GROUP_REVIEWED,
    TOILET_COORDINATE_CORRECTED,
    TOILET_REGION_CONFIRMED,
    PUBLIC_DATA_CHANGE_APPLIED,
    PUBLIC_DATA_CHANGE_KEPT,
    PUBLIC_DATA_CHANGE_DEFERRED,
    TOILET_DISPLAY_GROUP_SAVED,
    TOILET_DISPLAY_GROUP_DELETED,
    TOILET_ADMIN_UPDATED
}
