CREATE TABLE toilet_report (
    report_id BIGINT NOT NULL AUTO_INCREMENT,
    toilet_id BIGINT NOT NULL,
    reporter_user_id BIGINT NOT NULL,
    report_type VARCHAR(30) NOT NULL,
    proposed_latitude DECIMAL(10,7) NULL,
    proposed_longitude DECIMAL(10,7) NULL,
    proposed_road_address VARCHAR(255) NULL,
    proposed_open_time VARCHAR(50) NULL,
    reason VARCHAR(500) NOT NULL,
    status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    active_request_key CHAR(64) NULL,
    reviewed_by_user_id BIGINT NULL,
    reviewed_at DATETIME NULL,
    review_note VARCHAR(500) NULL,
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (report_id),
    UNIQUE KEY uk_report_active_request (active_request_key),
    KEY idx_report_status_created (status, created_at),
    KEY idx_report_toilet_created (toilet_id, created_at),
    CONSTRAINT fk_report_toilet FOREIGN KEY (toilet_id) REFERENCES toilet (toilet_id),
    CONSTRAINT fk_reporter_user FOREIGN KEY (reporter_user_id) REFERENCES app_user (user_id),
    CONSTRAINT fk_report_reviewer FOREIGN KEY (reviewed_by_user_id) REFERENCES app_user (user_id)
);

CREATE TABLE coordinate_revision (
    coordinate_revision_id BIGINT NOT NULL AUTO_INCREMENT,
    toilet_id BIGINT NOT NULL,
    report_id BIGINT NOT NULL,
    previous_latitude DECIMAL(10,7) NULL,
    previous_longitude DECIMAL(10,7) NULL,
    applied_latitude DECIMAL(10,7) NOT NULL,
    applied_longitude DECIMAL(10,7) NOT NULL,
    previous_road_address VARCHAR(255) NULL,
    applied_road_address VARCHAR(255) NOT NULL,
    applied_by_user_id BIGINT NOT NULL,
    applied_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    source VARCHAR(30) NOT NULL DEFAULT 'USER_REPORT_APPROVED',
    PRIMARY KEY (coordinate_revision_id),
    UNIQUE KEY uk_revision_report (report_id),
    KEY idx_revision_toilet_applied (toilet_id, applied_at),
    CONSTRAINT fk_revision_toilet FOREIGN KEY (toilet_id) REFERENCES toilet (toilet_id),
    CONSTRAINT fk_revision_report FOREIGN KEY (report_id) REFERENCES toilet_report (report_id),
    CONSTRAINT fk_revision_admin FOREIGN KEY (applied_by_user_id) REFERENCES app_user (user_id)
);
